### ISSUE TITLE
python3 msgpack_monitor.py

### ISSUE THREAD

**Issue by kaankaval** [vindolin/python_ebyte_lora#2]
output:
120
120
126
-30
Traceback (most recent call last):
  File "msgpack_monitor.py", line 18, in <module>
    for obj_ in unpacker:
  File "msgpack/_unpacker.pyx", line 518, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 443, in msgpack._cmsgpack.Unpacker._unpack
ValueError: int is not allowed for map key

expected output was:
ofis
26.20
6.00

what should i do for it?

**Comment by vindolin** [comment]
Looks like this was changed in msgpack 1.0 https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10.
You have to pass `strict_map_key=False` as a parameter to `msgpack.Unpacker()` if you want to use non strings as keys.

```
unpacker = msgpack.Unpacker(strict_map_key=False)
```
